// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zubovexfipdrcqdrgkdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Ym92ZXhmaXBkcmNxZHJna2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDMwMjYsImV4cCI6MjA2OTgxOTAyNn0.jLr6JbNmShBMcza3X0thEnzfaSOfTo9_hwMF8jwCDZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});